export const COURSE_GET_REQUEST = "COURSE_GET_REQUEST";
export const COURSE_GET_SUCCESS = "COURSE_GET_SUCCESS";
export const COURSE_GET_ERROR = "COURSE_GET_ERROR";

// Course Create
export const COURSE_CREATE_REQUEST = "COURSE_CREATE_REQUEST";
export const COURSE_CREATE_SUCCESS = "COURSE_CREATE_SUCCESS";
export const COURSE_CREATE_ERROR = "COURSE_CREATE_ERROR";
export const COURSE_CREATE_RESET = "COURSE_CREATE_RESET";

// Course Delete
export const COURSE_DELETE_REQUEST = "COURSE_DELETE_REQUEST";
export const COURSE_DELETE_SUCCESS = "COURSE_DELETE_SUCCESS";
export const COURSE_DELETE_ERROR = "COURSE_DELETE_ERROR";
export const COURSE_DELETE_RESET = "COURSE_DELETE_RESET";

// Course Quiz
export const COURSE_QUIZ_GET_REQUEST = "COURSE_QUIZ_GET_REQUEST";
export const COURSE_QUIZ_GET_SUCCESS = "COURSE_QUIZ_GET_SUCCESS";
export const COURSE_QUIZ_GET_ERROR = "COURSE_QUIZ_GET_ERROR";

// Teacher Course
export const TEACHER_COURSE_GET_REQUEST = "TEACHER_COURSE_GET_REQUEST";
export const TEACHER_COURSE_GET_SUCCESS = "TEACHER_COURSE_GET_SUCCESS";
export const TEACHER_COURSE_GET_ERROR = "TEACHER_COURSE_GET_ERROR";

// Quiz Create
export const QUIZ_CREATE_REQUEST = "QUIZ_CREATE_REQUEST";
export const QUIZ_CREATE_SUCCESS = "QUIZ_CREATE_SUCCESS";
export const QUIZ_CREATE_ERROR = "QUIZ_CREATE_ERROR";
export const QUIZ_CREATE_RESET = "QUIZ_CREATE_RESET";
